# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-06 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20161104_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='partner_id',
        ),
        migrations.AddField(
            model_name='partner',
            name='postal_code',
            field=models.IntegerField(default=50001),
            preserve_default=False,
        ),
    ]
