# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-09 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_auto_20161106_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='dni',
            field=models.CharField(help_text='DNI', max_length=9),
        ),
    ]
