# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-09 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_auto_20161109_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='dni',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='partner',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='partner',
            name='postal_code',
            field=models.CharField(max_length=5),
        ),
    ]
